### ISSUE TITLE
The epipolarLine function

### ISSUE THREAD

**Issue by photopea** [DzReal/8-point-algorithm-MATLAB#1]
Hi,  I am trying to use your code in Octave.

Could you implement the epipolarLine function with your own code, instead of calling a function? It is the only missing piece in helping me understand the Fundamental matrix.

**Comment by fredzzhang** [comment]
Hi,

I've stopped maintaining this repository for a while. The function `epipolarLine` is a MATLAB built-in function. You can find more details [here](https://www.mathworks.com/help/vision/ref/epipolarline.html#mw_1f7a05f9-8166-4bee-868a-12d4cd5177a6). If you want to know more about fundamental matrix, you might want to read chapter 9 of the book _Multiple view geometry in computer vision_ by Richard Hartley. The pdf is freely available online.

Cheers,
Fred
