### ISSUE TITLE
The code is absolutely wrong

### ISSUE THREAD

**Issue by photopea** [DzReal/8-point-algorithm-MATLAB#2]
If anybody is going to use this implementation, you should know, that it is completely wrong. The output matrix is not a fundamental matrix. So epipolar lines and epipoles you get from it are also wrong.

**Comment by fredzzhang** [comment]
Hi,

To respond to your concern, the code indeed does not return the fundamental matrix, but the essential matrix. I think this is rather clear in the documentation, partially shown below. 

```
% Function Introdution:
% Given a set of correspondences between two images and the intrisic matrix
% of the calibrated camera for both views, compute the essential matrix
% associated with the epipolar geometry using eight points
```

The essential matrix is computed from the fundamental matrix and intrinsics of the camera, denoted by K. If you want the fundamental matrix instead, simply pass an identity matrix as the intrinsic matrix. I hope this helps. Let me know if you have other questions.

Cheers,
Fred

**Comment by photopea** [comment]
I mean, your implementation is incorrect. Specifically, the line 59 here: https://github.com/DzReal/Normalized-Eight-Point-Algorithm/blob/master/eightPoint.m

Try to run your code on more than just one image. You will see, that the epipolar lines and the epipole, which your code finds, are absolutely wrong.

**Comment by fredzzhang** [comment]
Hi,

On real images, the results returned will depend on the quality of the correspondences. This implementation did not incorporate any robust algorithms like RANSAC, but uses only the first 8 point correspondences among however many that have been extracted. So, if there happens to be a significant proportion of outliers in the first 8 correspondences, I'd expect the computed essential matrix to be awfully wrong. Same goes to epipoles. I'd suggest going through your point correspondences to get a feeling of the quality and maybe manually select some good matches. That'll help a lot.

Although these code are a few years old, I can assure you the algorithm is correct. You can try running the synthetic tests. Under zero noise, the algorithm gives perfect results.

In general, the 8-point algorithm is linear and extremely fast but not as robust as some other variants like 5-point algorithm. In case you want to try it, [here](https://github.com/SergioRAgostinho/five_point_algorithm) is an implementation of the 5-point algorithm.

Cheers,
Fred

**Comment by photopea** [comment]
Your implementation is incorrect. I know it, because unlike you, I executed it on many other images, and compared witho other implementations of the 8-point algorithm (using the same input). Your implementation always puts the epipole somewhere between the 8 points, even when it has to be outside the image.

I understand, that you are too busy to fix it. But you should at least delete it from GitHub. Many people might try to use it, and will spend hours trying to find an error in their code, until realising, that the error is in your code.

**Comment by photopea** [comment]
But if you still want to fix your code, rewrite the line 59 in your code according to lie 50 here: https://github.com/MareArts/8point-algorithm/blob/master/GetFmatrix_Final.m , the formula is totally different.

But most importantly, always compare the output of your implementation with other implementations.

**Comment by fredzzhang** [comment]
Hi,

I can see your frustration. Sorry if the code didn't work for you. But line 59 is correct. It is simply imposing rank 2 in an extended form. The maths is the same as line 50 in the script you mentioned. Here the third singular value is zeroed out when reconstructing the fundamental matrix, simple and elegant.

```matlab
49    [U D V] = svd(F);
50    F=U*diag([D(1,1) D(2,2) 0])*V';
```
My code was a bit clumsy. But it does the same thing, enforcing the fundamental matrix to be rank deficient (rank 2 specifically).
```matlab
58    [U, S, V] = svd(fMatrix);
59    fMatrix = U(:, 1) * S(1,1) * transpose(V(:, 1)) + U(:, 2) * S(2,2) * transpose(V(:, 2));
```

If you don't understand the maths, try to single out these two lines in both scripts and force `F` and `fMatrix` to be the same before SVD, the output would be the same. One difference I noticed though, is that @MareArts constructed the normalisation matrix based on the dimension of the image, while I did it based on the distribution of the 8 selected points. I guess that's a mistake on my end. Only using 8 points to compute the normalisation matrix would for sure be susceptible to noise. That might be one reason behind inaccurate epipoles.

Anyways, I'll see if can find some time to pinpoint the problem. Let me know if you have other concerns.

Thanks,
Fred

**Comment by photopea** [comment]
After I look at it now, your matrix formula really does correspond to the other formula I mentioned.

Do you really think the problem is just in the normalization? Your code gave a lot different matrices than the other one, even when supplied with more than eight input points.

**Comment by fredzzhang** [comment]
Hi,

The code here was part of an old undergraduate project. I'm not inclined to spend time fixing the problem any more. I've added warnings of inaccurate results in the description, which can be seen at the very top of the repository.

Sorry for the inconvenience it caused you.

Cheers,
Fred
